export const RECIPE_REQUEST = 'RECIPE_REQUEST';
export const RECIPE_SUCCESS = 'RECIPE_SUCCESS';
export const RECIPE_FAILURE = 'RECIPE_FAILURE';

export const YOU_MAY_LIKE_REQUEST = 'YOU_MAY_LIKE_REQUEST';
export const YOU_MAY_LIKE_SUCCESS = 'YOU_MAY_LIKE_SUCCESS';
export const YOU_MAY_LIKE_FAILURE = 'YOU_MAY_LIKE_FAILURE';

export const INGREDIENT_BASED_REQUEST = 'INGREDIENT_BASED_REQUEST';
export const INGREDIENT_BASED_SUCCESS = 'INGREDIENT_BASED_SUCCESS';
export const INGREDIENT_BASED_FAILURE = 'INGREDIENT_BASED_FAILURE';

export const SIMILAR_RECIPES_REQUEST = 'SIMILAR_RECIPES_REQUEST';
export const SIMILAR_RECIPES_SUCCESS = 'SIMILAR_RECIPES_SUCCESS';
export const SIMILAR_RECIPES_FAILURE = 'SIMILAR_RECIPES_FAILURE';

export const INGREDIENT_SEARCH_REQUEST = 'INGREDIENT_SEARCH_REQUEST';
export const INGREDIENT_SEARCH_SUCCESS = 'INGREDIENT_SEARCH_SUCCESS';
export const INGREDIENT_SEARCH_FAILURE = 'INGREDIENT_SEARCH_FAILURE';

export const RECIPES_SEARCH_REQUEST = 'RECIPES_SEARCH_REQUEST';
export const RECIPES_SEARCH_SUCCESS = 'RECIPES_SEARCH_SUCCESS';
export const RECIPES_SEARCH_FAILURE = 'RECIPES_SEARCH_FAILURE';
